name: Run CheckApproval CheckBug CheckLint tasks

on:
  pull_request:
    types: [ opened, submitted, edited, synchronize, reopened, edited]
    branches: '**'
jobs:  
  TriggerWorkfows:
    uses: projectceladon/celadonworkflows/.github/workflows/Triggerall.yml@main
    with:
      PR_EVENT: ${{ github.event.action }}
      PR_URL: https://github.com/${{github.repository}}/pull/${{ github.event.number }}
    secrets: inherit
